import { COLORS } from './theme';
import { Job } from '../types';

export const FALLBACK_SEED_JOBS: Job[] = [
  {
    id: 'j1',
    employer_id: 'emp1',
    company: 'Tata AutoComp Systems',
    companyLogo: '',
    company_color: COLORS.primary,
    title: 'Senior MIG Welder',
    industry: 'Automotive',
    location: 'Chakan MIDC, Pune',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 3,
    minExperience: 3,
    max_experience: 6,
    maxExperience: 6,
    salary_min: 240000,
    salaryMin: 240000,
    salary_max: 360000,
    salaryMax: 360000,
    openings: 15,
    description: 'Required experienced MIG Welder for automotive parts welding. Should be able to read drawings and perform structural quality welding.',
    responsibilities: [
      'Perform MIG welding on assemblies',
      'Follow safety guidelines on the shop floor',
      'Verify weld dimensions using calipers and gauges'
    ],
    requirements: [
      'ITI Welder trade completed',
      '3+ years industrial welding experience',
      'Pass weld test on site'
    ],
    skills: ['MIG Welding', 'Blueprint Reading', 'Shop Safety', 'TIG Welding'],
    perks: ['Canteen Subsidized', 'PF & ESIC', 'Overtime Pay', 'Transport Facility'],
    featured: true,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 86400000).toISOString(),
    views: 142,
    trade: 'Welder',
    midc_zone: 'Chakan MIDC',
    shift_details: 'Day Shift (8 AM - 5 PM)',
    overtime: true,
    canteen: true,
    bus_facility: true,
    busFacility: true,
    accommodation: true
  },
  {
    id: 'j2',
    employer_id: 'emp1',
    company: 'Bharat Forge Ltd',
    companyLogo: '',
    company_color: '#B45309',
    title: 'CNC & VMC Machine Operator',
    industry: 'Manufacturing',
    location: 'Bhosari MIDC, Pune',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 1,
    minExperience: 1,
    max_experience: 3,
    maxExperience: 3,
    salary_min: 180000,
    salaryMin: 180000,
    salary_max: 260000,
    salaryMax: 260000,
    openings: 30,
    description: 'Hiring CNC and VMC machine operators for heavy forge division. Daily production targets, component loading/unloading and quality checks using Vernier Calipers.',
    responsibilities: [
      'Operate CNC turning centers and VMC machines',
      'Perform checks using micrometers and height gauges',
      'Maintain daily production registers'
    ],
    requirements: [
      'ITI Machinist / Turner / Fitter trade',
      '1+ years CNC operation experience'
    ],
    skills: ['CNC Operation', 'Vernier Calipers', 'Micrometer', 'VMC Programming'],
    perks: ['Subsidized Canteen', 'Bus facility available', 'OT Double Rate'],
    featured: true,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 172800000).toISOString(),
    views: 289,
    trade: 'CNC Operator',
    midc_zone: 'Bhosari MIDC',
    shift_details: 'Rotational (Shift A / B)',
    overtime: true,
    canteen: true,
    bus_facility: true,
    busFacility: true,
    accommodation: false
  },
  {
    id: 'j3',
    employer_id: 'emp2',
    company: 'Thermax Industrial',
    companyLogo: '',
    company_color: '#047857',
    title: 'Maintenance Electrician',
    industry: 'Engineering',
    location: 'Bhosari MIDC, Pune',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 2,
    minExperience: 2,
    max_experience: 5,
    maxExperience: 5,
    salary_min: 220000,
    salaryMin: 220000,
    salary_max: 320000,
    salaryMax: 320000,
    openings: 8,
    description: 'Immediate requirement for Industrial Maintenance Electrician for boiler plant equipment maintenance and PLC panel troubleshooting.',
    responsibilities: [
      'Electrical maintenance of industrial machinery',
      'Troubleshoot control panels, motors, and drives',
      'Maintain preventive maintenance schedule'
    ],
    requirements: [
      'ITI Electrician / Wireman License Holder',
      '2+ years experience in plant electrical maintenance'
    ],
    skills: ['PLC Panels', 'Electrical Troubleshooting', 'Motor Control', 'Wiring'],
    perks: ['Medical Insurance', 'Free Canteen', 'Performance Bonus'],
    featured: false,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 259200000).toISOString(),
    views: 195,
    trade: 'Electrician',
    midc_zone: 'Bhosari MIDC',
    shift_details: 'Rotational (Shift A / B / C)',
    overtime: true,
    canteen: true,
    bus_facility: true,
    busFacility: true,
    accommodation: true
  },
  {
    id: 'j4',
    employer_id: 'emp2',
    company: 'Endurance Technologies',
    companyLogo: '',
    company_color: '#4F46E5',
    title: 'Assembly Fitter',
    industry: 'Automotive',
    location: 'Waluj MIDC, Chhatrapati Sambhajinagar',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 0,
    minExperience: 0,
    max_experience: 2,
    maxExperience: 2,
    salary_min: 160000,
    salaryMin: 160000,
    salary_max: 220000,
    salaryMax: 220000,
    openings: 25,
    description: 'Looking for mechanical assembly fitters for transmission component assembly line. Freshers with ITI Fitter trade are welcome to apply.',
    responsibilities: [
      'Assemble automotive transmission components on conveyor line',
      'Use pneumatic tools and torque wrenches',
      'Follow 5S standards at workplace'
    ],
    requirements: [
      'ITI Fitter trade (NCVT / SCVT)',
      '0-2 years experience'
    ],
    skills: ['Torque Wrench', 'Mechanical Assembly', '5S Standards', 'Blueprint Reading'],
    perks: ['Free Bus Transport', 'Subsidized Canteen', 'Joining Bonus'],
    featured: true,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 345600000).toISOString(),
    views: 310,
    trade: 'Fitter',
    midc_zone: 'Waluj MIDC',
    shift_details: 'Day Shift (8 AM - 5 PM)',
    overtime: true,
    canteen: true,
    bus_facility: true,
    busFacility: true,
    accommodation: true
  },
  {
    id: 'j5',
    employer_id: 'emp3',
    company: 'Varroc Engineering',
    companyLogo: '',
    company_color: '#DC2626',
    title: 'Quality Control Inspector',
    industry: 'Automotive',
    location: 'Waluj MIDC, Chhatrapati Sambhajinagar',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 2,
    minExperience: 2,
    max_experience: 4,
    maxExperience: 4,
    salary_min: 210000,
    salaryMin: 210000,
    salary_max: 300000,
    salaryMax: 300000,
    openings: 10,
    description: 'Perform incoming, in-process, and final quality inspection of molded plastic and metal auto parts.',
    responsibilities: [
      'Check part dimensions using CMM and profile projector',
      'Prepare PDI reports and rejection notes',
      'Coordinate with production team for quality resolution'
    ],
    requirements: [
      'Diploma / ITI Mechanical',
      '2+ years experience in QA/QC'
    ],
    skills: ['Quality Inspection', 'CMM Inspection', 'Vernier Caliper', 'PDI Reporting'],
    perks: ['ESI & PF', 'Annual Hike', 'Canteen Facility'],
    featured: false,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 432000000).toISOString(),
    views: 178,
    trade: 'Quality Inspector',
    midc_zone: 'Waluj MIDC',
    shift_details: 'Rotational (Shift A / B)',
    overtime: false,
    canteen: true,
    bus_facility: true,
    busFacility: true,
    accommodation: false
  },
  {
    id: 'j6',
    employer_id: 'emp4',
    company: 'Galaxy Care Hospital',
    companyLogo: '',
    company_color: '#EF4444',
    title: 'Staff Nurse (ICU / General Ward)',
    industry: 'Healthcare',
    location: 'Pune City',
    job_type: 'Full-time',
    jobType: 'Full-Time',
    work_mode: 'On-site',
    workMode: 'Onsite',
    min_experience: 1,
    minExperience: 1,
    max_experience: 5,
    maxExperience: 5,
    salary_min: 240000,
    salaryMin: 240000,
    salary_max: 380000,
    salaryMax: 380000,
    openings: 12,
    description: 'Urgent requirement for GNM / B.Sc Nursing staff for ICU, OT, and general wards. Competitive salary with hostel accommodation.',
    responsibilities: [
      'Patient care and medication administration',
      'Monitor vital signs and assist doctors in procedures',
      'Maintain patient care records'
    ],
    requirements: [
      'GNM / B.Sc Nursing with MNC Registration',
      '1+ years hospital nursing experience'
    ],
    skills: ['Patient Care', 'ICU Care', 'Vital Signs Monitoring', 'Medication Administration'],
    perks: ['Hostel Accommodation', 'PF & ESI', 'Overtime Pay'],
    featured: true,
    status: 'APPROVED',
    posted_at: new Date(Date.now() - 518400000).toISOString(),
    views: 412,
    trade: 'Hospital Jobs',
    midc_zone: 'Pune City',
    shift_details: 'Rotational Shifts',
    overtime: true,
    canteen: true,
    bus_facility: false,
    busFacility: false,
    accommodation: true
  }
];
