export interface CompanySeedData {
  name: string;
  logo: string;
  color: string;
  industry: string;
  description: string;
  website: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  latitude: number;
  longitude: number;
  email: string;
  phone: string;
  companySize: string;
  foundedYear: number;
  midcZone: string;
}

export const CSN_COMPANIES: CompanySeedData[] = [
  // 1-25: INDUSTRIAL & MANUFACTURING
  {
    name: 'Bajaj Auto Ltd',
    logo: 'https://logo.clearbit.com/bajajauto.com',
    color: '#003399',
    industry: 'Automotive Manufacturing',
    description: 'Premier two-wheeler and three-wheeler manufacturing facility producing Pulsar, Chetak EV, and Commercial RE auto rickshaws at Waluj plant.',
    website: 'https://www.bajajauto.com',
    address: 'Plot No. A-1, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8455,
    longitude: 75.2285,
    email: 'careers.waluj@bajajauto.co.in',
    phone: '+91 240 2554000',
    companySize: '10,000+ employees',
    foundedYear: 1945,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Škoda Auto Volkswagen India',
    logo: 'https://logo.clearbit.com/skoda-auto.com',
    color: '#4BA829',
    industry: 'Automotive Manufacturing',
    description: 'State-of-the-art passenger vehicle assembly manufacturing Kushaq, Slavia, Taigun, and Virtus models for domestic and global export markets.',
    website: 'https://www.skoda-vw.co.in',
    address: 'Plot A-1, Shendra Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431154',
    latitude: 19.8655,
    longitude: 75.5205,
    email: 'hr.shendra@skoda-vw.co.in',
    phone: '+91 240 6631000',
    companySize: '5,000-10,000 employees',
    foundedYear: 2001,
    midcZone: 'Shendra MIDC'
  },
  {
    name: 'Wockhardt Ltd',
    logo: 'https://logo.clearbit.com/wockhardt.com',
    color: '#D9252A',
    industry: 'Pharmaceuticals',
    description: 'Global pharmaceutical and biotechnology major manufacturing active pharmaceutical ingredients (APIs), sterile injectables, and formulations.',
    website: 'https://www.wockhardt.com',
    address: 'L-1, Chikalthana MIDC Area, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8785,
    longitude: 75.3855,
    email: 'careers.aurangabad@wockhardt.com',
    phone: '+91 240 6637444',
    companySize: '5,000-10,000 employees',
    foundedYear: 1967,
    midcZone: 'Chikalthana MIDC'
  },
  {
    name: 'CEAT Tyres Ltd',
    logo: 'https://logo.clearbit.com/ceat.com',
    color: '#E30613',
    industry: 'Tyre Manufacturing',
    description: 'RPG Group company manufacturing high-performance radial tyres for truck, bus, agricultural, and passenger cars in Waluj.',
    website: 'https://www.ceat.com',
    address: 'Plot No. H-3, Waluj MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8412,
    longitude: 75.2341,
    email: 'hr.waluj@ceat.com',
    phone: '+91 240 2552400',
    companySize: '1,000-5,000 employees',
    foundedYear: 1958,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Siemens Limited',
    logo: 'https://logo.clearbit.com/siemens.com',
    color: '#009999',
    industry: 'Electrical & Industrial Automation',
    description: 'Global engineering powerhouse manufacturing medium voltage switchgears, industrial circuit breakers, and power distribution systems.',
    website: 'https://www.siemens.co.in',
    address: 'Plot B-5, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8490,
    longitude: 75.2210,
    email: 'recruitment.aurangabad@siemens.com',
    phone: '+91 240 6642000',
    companySize: '5,000-10,000 employees',
    foundedYear: 1847,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Endurance Technologies Ltd',
    logo: 'https://logo.clearbit.com/endurancegroup.com',
    color: '#0A2540',
    industry: 'Auto Components',
    description: 'Leading automotive component manufacturer producing aluminium die-castings, suspension systems, transmission components, and braking systems.',
    website: 'https://www.endurancegroup.com',
    address: 'Plot No. E-92, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8430,
    longitude: 75.2260,
    email: 'careers@endurancegroup.com',
    phone: '+91 240 2552860',
    companySize: '5,000-10,000 employees',
    foundedYear: 1985,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Varroc Engineering Ltd',
    logo: 'https://logo.clearbit.com/varroc.com',
    color: '#C8102E',
    industry: 'Auto Components & Lighting',
    description: 'Global Tier-1 automotive component group manufacturing exterior lighting, polymer components, electrical systems, and precision forgings.',
    website: 'https://www.varroc.com',
    address: 'Plot No. L-4, MIDC Industrial Area, Waluj',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8480,
    longitude: 75.2320,
    email: 'careers@varroc.com',
    phone: '+91 240 6652400',
    companySize: '5,000-10,000 employees',
    foundedYear: 1990,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Garware Technical Fibres Ltd',
    logo: 'https://logo.clearbit.com/garwarefibres.com',
    color: '#005A9C',
    industry: 'Technical Textiles & Fibres',
    description: 'Leading technical textiles manufacturer producing synthetic cordage, aquaculture nets, coated fabrics, and geo-synthetics.',
    website: 'https://www.garwarefibres.com',
    address: 'Plot No. 3, Chikalthana Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8795,
    longitude: 75.3810,
    email: 'hr.aurangabad@garwarefibres.com',
    phone: '+91 240 2484311',
    companySize: '1,000-5,000 employees',
    foundedYear: 1976,
    midcZone: 'Chikalthana MIDC'
  },
  {
    name: 'Johnson & Johnson India',
    logo: 'https://logo.clearbit.com/jnj.com',
    color: '#D51900',
    industry: 'FMCG & Consumer Health',
    description: 'Manufacturing unit for personal care, baby products, sanitary hygiene goods, and consumer healthcare products.',
    website: 'https://www.jnjindia.com',
    address: 'Plot B-15, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8390,
    longitude: 75.2230,
    email: 'careers.aurangabad@jnj.com',
    phone: '+91 240 2554312',
    companySize: '1,000-5,000 employees',
    foundedYear: 1886,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Goodyear India Ltd',
    logo: 'https://logo.clearbit.com/goodyear.com',
    color: '#002664',
    industry: 'Tyre & Rubber Manufacturing',
    description: 'World-renowned tyre manufacturer producing farm tyres, off-the-road (OTR) commercial tyres, and industrial rubber products.',
    website: 'https://www.goodyear.co.in',
    address: 'Plot No. K-1, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8405,
    longitude: 75.2295,
    email: 'careers.waluj@goodyear.com',
    phone: '+91 240 2552000',
    companySize: '1,000-5,000 employees',
    foundedYear: 1898,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Perkins India Pvt Ltd',
    logo: 'https://logo.clearbit.com/perkins.com',
    color: '#FFCC00',
    industry: 'Diesel & Gas Engines',
    description: 'Caterpillar subsidiary manufacturing 400 series and 1100 series heavy-duty diesel engines for industrial power generation.',
    website: 'https://www.perkins.com',
    address: 'Plot No. A-2, Shendra MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431154',
    latitude: 19.8670,
    longitude: 75.5230,
    email: 'careers_india@perkins.com',
    phone: '+91 240 6634000',
    companySize: '500-1,000 employees',
    foundedYear: 1932,
    midcZone: 'Shendra MIDC'
  },
  {
    name: 'Liebherr Appliances India',
    logo: 'https://logo.clearbit.com/liebherr.com',
    color: '#FFD100',
    industry: 'Consumer Electronics & Refrigeration',
    description: 'German refrigeration specialist manufacturing premium refrigerators, freezers, and wine storage solutions in AURIC Shendra.',
    website: 'https://home.liebherr.com',
    address: 'Plot No. B-3, AURIC Smart City, Shendra',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431154',
    latitude: 19.8690,
    longitude: 75.5260,
    email: 'info.laj@liebherr.com',
    phone: '+91 240 6650000',
    companySize: '500-1,000 employees',
    foundedYear: 1949,
    midcZone: 'AURIC Shendra'
  },
  {
    name: 'Crompton Greaves Consumer',
    logo: 'https://logo.clearbit.com/crompton.co.in',
    color: '#00529B',
    industry: 'Electrical Appliances',
    description: 'Manufacturing facility producing energy-efficient ceiling fans, industrial pumps, LED luminaires, and home appliances.',
    website: 'https://www.crompton.co.in',
    address: 'Plot No. C-1, Waluj MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8465,
    longitude: 75.2195,
    email: 'hr.aurangabad@crompton.co.in',
    phone: '+91 240 2554500',
    companySize: '1,000-5,000 employees',
    foundedYear: 1937,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Sterlite Technologies Ltd',
    logo: 'https://logo.clearbit.com/stl.tech',
    color: '#5C2D91',
    industry: 'Optical Fibre & Telecommunications',
    description: 'Global optical cable and broadband technology company producing high-capacity optical fibres and network equipment.',
    website: 'https://www.stl.tech',
    address: 'Plot No. E-1, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8425,
    longitude: 75.2315,
    email: 'careers@stl.tech',
    phone: '+91 240 2558000',
    companySize: '1,000-5,000 employees',
    foundedYear: 1988,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Cosmo First Ltd',
    logo: 'https://logo.clearbit.com/cosmofirst.com',
    color: '#002B49',
    industry: 'Packaging Films & Specialty Polymers',
    description: 'Global leader in BOPP packaging films, synthetic paper, thermal lamination films, and specialty polymer coatings.',
    website: 'https://www.cosmofirst.com',
    address: 'Plot No. B-14, Waluj MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8475,
    longitude: 75.2245,
    email: 'hr.aurangabad@cosmofirst.com',
    phone: '+91 240 2554611',
    companySize: '1,000-5,000 employees',
    foundedYear: 1981,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Grind Master Group',
    logo: 'https://logo.clearbit.com/grindmaster.co.in',
    color: '#E31B23',
    industry: 'Robotics & Metal Finishing Machines',
    description: 'Pioneer in specialized metal finishing machines, micro-finishing, robotic deburring, and abrasive belt grinding machinery.',
    website: 'https://www.grindmaster.co.in',
    address: 'Plot No. B-11, Railway Station MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431005',
    latitude: 19.8610,
    longitude: 75.3160,
    email: 'careers@grindmaster.co.in',
    phone: '+91 240 2374100',
    companySize: '500-1,000 employees',
    foundedYear: 1984,
    midcZone: 'Railway Station MIDC'
  },
  {
    name: 'NRB Bearings Ltd',
    logo: 'https://logo.clearbit.com/nrbbearings.com',
    color: '#003366',
    industry: 'Bearings & Precision Engineering',
    description: 'Leading needle roller bearing, cylindrical bearing, and precision steel ball manufacturer supplying top automotive OEMs.',
    website: 'https://www.nrbbearings.com',
    address: 'Plot No. E-40, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8438,
    longitude: 75.2272,
    email: 'hr.waluj@nrbbearings.in',
    phone: '+91 240 2554780',
    companySize: '1,000-5,000 employees',
    foundedYear: 1965,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Can-Pack India Pvt Ltd',
    logo: 'https://logo.clearbit.com/canpack.com',
    color: '#E2001A',
    industry: 'Metal Packaging & Cans',
    description: 'World leader in aluminium beverage can manufacturing supplying top global brewery and soft drink packaging brands.',
    website: 'https://www.canpack.com',
    address: 'Plot No. A-7, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8498,
    longitude: 75.2225,
    email: 'hr.india@canpack.com',
    phone: '+91 240 6636000',
    companySize: '500-1,000 employees',
    foundedYear: 1992,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Sanjeev Auto Parts',
    logo: 'https://logo.clearbit.com/sanjeevauto.com',
    color: '#1E40AF',
    industry: 'Precision Machining & Forging',
    description: 'Specialist manufacturer of transmission shafts, gears, automotive forgings, and CNC machined sub-assemblies.',
    website: 'https://www.sanjeevauto.com',
    address: 'Plot No. B-5, Waluj Industrial Area, MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8445,
    longitude: 75.2305,
    email: 'careers@sanjeevauto.com',
    phone: '+91 240 2553100',
    companySize: '1,000-5,000 employees',
    foundedYear: 1988,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Badve Engineering Ltd',
    logo: 'https://logo.clearbit.com/badvegroup.com',
    color: '#B91C1C',
    industry: 'Sheet Metal & Plastics',
    description: 'Major Tier-1 auto vendor manufacturing chassis frames, exhaust systems, plastic molded parts, and EV battery enclosures.',
    website: 'https://www.badvegroup.com',
    address: 'Plot No. D-39, Waluj MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8418,
    longitude: 75.2252,
    email: 'careers@badvegroup.com',
    phone: '+91 240 2555000',
    companySize: '5,000-10,000 employees',
    foundedYear: 1996,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Dhoot Transmission Pvt Ltd',
    logo: 'https://logo.clearbit.com/dhoottransmission.com',
    color: '#047857',
    industry: 'Wiring Harness & Automotive Electronics',
    description: 'Leading manufacturer of automotive wiring harnesses, electronic sensors, battery cables, and switches for 2W, 4W, and commercial vehicles.',
    website: 'https://www.dhoottransmission.com',
    address: 'Plot No. Gut 100, Farola, Paithan Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431107',
    latitude: 19.8120,
    longitude: 75.3015,
    email: 'hr@dhoottransmission.com',
    phone: '+91 240 6625000',
    companySize: '5,000-10,000 employees',
    foundedYear: 1999,
    midcZone: 'Paithan Road'
  },
  {
    name: 'Metalman Auto Pvt Ltd',
    logo: 'https://logo.clearbit.com/metalmanauto.com',
    color: '#374151',
    industry: 'Sheet Metal & Tubular Fabrication',
    description: 'Tier-1 supplier of heavy tubular fabrications, motorcycle frames, swingarms, and sheet metal stampings.',
    website: 'https://www.metalmanauto.com',
    address: 'Plot No. E-11, Waluj MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8458,
    longitude: 75.2238,
    email: 'hr.waluj@metalmanauto.com',
    phone: '+91 240 2552900',
    companySize: '1,000-5,000 employees',
    foundedYear: 1986,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Expert Global Solutions',
    logo: 'https://logo.clearbit.com/expertgroup.com',
    color: '#1D4ED8',
    industry: 'Engineering R&D & IT Services',
    description: 'Digital transformation, CAD/CAM product engineering, embedded systems, and Industry 4.0 software solutions provider.',
    website: 'https://www.expertgroup.com',
    address: 'Plot No. 12, IT Park, Chikalthana MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8805,
    longitude: 75.3880,
    email: 'careers@expertgroup.com',
    phone: '+91 240 2482300',
    companySize: '500-1,000 employees',
    foundedYear: 1998,
    midcZone: 'Chikalthana MIDC'
  },
  {
    name: 'Radico NV Distilleries',
    logo: 'https://logo.clearbit.com/radiconv.com',
    color: '#7C2D12',
    industry: 'Distilled Spirits & Ethanol',
    description: 'Large-scale grain distillery producing extra neutral alcohol (ENA), industrial fuel ethanol, and premium spirits.',
    website: 'https://www.radiconv.com',
    address: 'Plot No. D-1, Shendra MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431154',
    latitude: 19.8640,
    longitude: 75.5250,
    email: 'info@radiconv.com',
    phone: '+91 240 2633000',
    companySize: '500-1,000 employees',
    foundedYear: 2007,
    midcZone: 'Shendra MIDC'
  },
  {
    name: 'Hindusthan National Glass',
    logo: 'https://logo.clearbit.com/hngil.com',
    color: '#065F46',
    industry: 'Glass Container Manufacturing',
    description: 'Leading container glass manufacturer producing glass bottles for pharmaceutical, food, beverage, and liquor industries.',
    website: 'https://www.hngil.com',
    address: 'Plot No. A-6, Waluj MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8402,
    longitude: 75.2218,
    email: 'hr.aurangabad@hngil.com',
    phone: '+91 240 2554100',
    companySize: '1,000-5,000 employees',
    foundedYear: 1946,
    midcZone: 'Waluj MIDC'
  },

  // 26-35: HEALTHCARE & PHARMA
  {
    name: 'MGM Medical College & Hospital',
    logo: 'https://logo.clearbit.com/mgmmcha.org',
    color: '#0284C7',
    industry: 'Healthcare & Medical Education',
    description: '1000+ bed premier NABH-accredited super-specialty teaching hospital, trauma centre, cardiac centre, and oncology institute.',
    website: 'https://www.mgmmcha.org',
    address: 'MGM Campus, N-6 CIDCO, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8755,
    longitude: 75.3625,
    email: 'careers@mgmmcha.org',
    phone: '+91 240 6601100',
    companySize: '1,000-5,000 employees',
    foundedYear: 1989,
    midcZone: 'CIDCO N-6'
  },
  {
    name: 'United CIIGMA Hospital',
    logo: 'https://logo.clearbit.com/ciigmahospitals.com',
    color: '#0D9488',
    industry: 'Healthcare & Multispecialty Hospital',
    description: 'State-of-the-art 300-bed NABH multi-superspecialty cardiac, neuro, organ transplant, and critical care hospital.',
    website: 'https://www.ciigmahospitals.com',
    address: 'Plot No. 1, Shahnoorwadi Parisar, Near CIDCO',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431005',
    latitude: 19.8665,
    longitude: 75.3340,
    email: 'hr@ciigmahospitals.com',
    phone: '+91 240 2364000',
    companySize: '500-1,000 employees',
    foundedYear: 2009,
    midcZone: 'Shahnoorwadi'
  },
  {
    name: 'Medicover Hospitals',
    logo: 'https://logo.clearbit.com/medicoverhospitals.in',
    color: '#2563EB',
    industry: 'Healthcare Services',
    description: 'European healthcare network facility delivering advanced tertiary care in cardiology, orthopedics, gastroenterology, and oncology.',
    website: 'https://www.medicoverhospitals.in',
    address: 'API Corner, Jalna Road, CIDCO N-4',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8762,
    longitude: 75.3680,
    email: 'careers.csn@medicoverhospitals.in',
    phone: '+91 240 6678000',
    companySize: '500-1,000 employees',
    foundedYear: 1995,
    midcZone: 'CIDCO N-4'
  },
  {
    name: 'Dr. Hedgewar Hospital',
    logo: 'https://logo.clearbit.com/hedgewar.org',
    color: '#D97706',
    industry: 'Healthcare & Charitable Hospital',
    description: '350-bed multi-specialty charitable hospital run by Babasaheb Ambedkar Vaidyakiya Prasarak Mandal offering affordable high-end medicine.',
    website: 'https://www.hedgewar.org',
    address: 'Garkheda Parisar, Near Gajanan Maharaj Temple',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431009',
    latitude: 19.8620,
    longitude: 75.3510,
    email: 'hr@hedgewar.org',
    phone: '+91 240 2331103',
    companySize: '500-1,000 employees',
    foundedYear: 1989,
    midcZone: 'Garkheda Parisar'
  },
  {
    name: 'Seth Nandlal Dhoot Hospital',
    logo: 'https://logo.clearbit.com/dhoothospital.com',
    color: '#059669',
    industry: 'Multispecialty Healthcare',
    description: '250-bed tertiary care facility equipped with advanced cath lab, dialysis unit, robotic surgery, and round-the-clock emergency ICU.',
    website: 'https://www.dhoothospital.com',
    address: 'A-1, Chikalthana, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8770,
    longitude: 75.3820,
    email: 'careers@dhoothospital.com',
    phone: '+91 240 2478000',
    companySize: '500-1,000 employees',
    foundedYear: 1998,
    midcZone: 'Chikalthana'
  },
  {
    name: 'Apex Multispecialty Hospital',
    logo: 'https://logo.clearbit.com/apexhospitalcsn.com',
    color: '#9333EA',
    industry: 'Healthcare',
    description: '150-bed acute trauma, laparoscopic surgery, critical care, pediatric ICU, and joint replacement hospital near Kranti Chowk.',
    website: 'https://www.apexhospitalcsn.com',
    address: 'Station Road, Near Kranti Chowk',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431001',
    latitude: 19.8712,
    longitude: 75.3215,
    email: 'contact@apexhospitalcsn.com',
    phone: '+91 240 2356700',
    companySize: '200-500 employees',
    foundedYear: 2012,
    midcZone: 'Kranti Chowk'
  },
  {
    name: 'Cipla Ltd',
    logo: 'https://logo.clearbit.com/cipla.com',
    color: '#E11D48',
    industry: 'Pharmaceutical Manufacturing',
    description: 'Global pharmaceutical giant producing respiratory inhalation formulations, oral solid dosages, and life-saving generic medicines.',
    website: 'https://www.cipla.com',
    address: 'Plot No. L-13, Waluj MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8432,
    longitude: 75.2288,
    email: 'careers.aurangabad@cipla.com',
    phone: '+91 240 2554400',
    companySize: '5,000-10,000 employees',
    foundedYear: 1935,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Ajanta Pharma Ltd',
    logo: 'https://logo.clearbit.com/ajantapharma.com',
    color: '#4F46E5',
    industry: 'Pharmaceutical Formulations',
    description: 'Specialty pharmaceutical company with USFDA-approved formulations facility producing ophthalmology, dermatology, and cardiology products.',
    website: 'https://www.ajantapharma.com',
    address: 'Plot No. B-4/5/6, Chikalthana MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8788,
    longitude: 75.3865,
    email: 'hr.aurangabad@ajantapharma.com',
    phone: '+91 240 6641000',
    companySize: '1,000-5,000 employees',
    foundedYear: 1973,
    midcZone: 'Chikalthana MIDC'
  },
  {
    name: 'Lupin Ltd',
    logo: 'https://logo.clearbit.com/lupin.com',
    color: '#0891B2',
    industry: 'Pharmaceuticals & Biotechnology',
    description: 'Leading global pharma company producing anti-tuberculosis medications, cephalosporins, cardiovascular formulations, and APIs.',
    website: 'https://www.lupin.com',
    address: 'Plot No. 101/102, Chikalthana MIDC Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8812,
    longitude: 75.3840,
    email: 'careers@lupin.com',
    phone: '+91 240 2484700',
    companySize: '5,000-10,000 employees',
    foundedYear: 1968,
    midcZone: 'Chikalthana MIDC'
  },
  {
    name: 'Sun Pharma Industries',
    logo: 'https://logo.clearbit.com/sunpharma.com',
    color: '#C026D3',
    industry: 'Pharmaceuticals',
    description: 'India’s largest pharmaceutical company manufacturing specialty neurology, oncology, gastroenterology, and chronic therapy drugs.',
    website: 'https://www.sunpharma.com',
    address: 'Plot No. E-2, Waluj MIDC Industrial Area',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8470,
    longitude: 75.2212,
    email: 'hr.waluj@sunpharma.com',
    phone: '+91 240 2552300',
    companySize: '10,000+ employees',
    foundedYear: 1983,
    midcZone: 'Waluj MIDC'
  },

  // 36-50: IT, RETAIL, EDUCATION, LOGISTICS & BANKING
  {
    name: 'TCS iON Digital Zone',
    logo: 'https://logo.clearbit.com/tcs.com',
    color: '#1E3A8A',
    industry: 'Information Technology & Assessments',
    description: 'Tata Consultancy Services digital hub managing enterprise IT infrastructure, SMB cloud services, and nationwide digital assessment centers.',
    website: 'https://www.tcsion.com',
    address: 'Gut No. 54, Near CIDCO Airport Road, Chikalthana',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8790,
    longitude: 75.3920,
    email: 'careers.csn@tcs.com',
    phone: '+91 240 6612000',
    companySize: '10,000+ employees',
    foundedYear: 1968,
    midcZone: 'Chikalthana'
  },
  {
    name: 'Avenue Supermarts (D-Mart)',
    logo: 'https://logo.clearbit.com/dmartindia.com',
    color: '#15803D',
    industry: 'Retail & Hypermarket',
    description: 'Nationwide hypermarket chain offering groceries, apparel, home appliances, footwear, and household utility products.',
    website: 'https://www.dmartindia.com',
    address: 'Plot No. 12, Town Centre, CIDCO N-2, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8750,
    longitude: 75.3580,
    email: 'hr.aurangabad@dmartindia.com',
    phone: '+91 240 2486600',
    companySize: '10,000+ employees',
    foundedYear: 2002,
    midcZone: 'CIDCO N-2'
  },
  {
    name: 'Reliance Retail Ltd',
    logo: 'https://logo.clearbit.com/relianceretail.com',
    color: '#DC2626',
    industry: 'Retail & Commerce',
    description: 'India’s largest retailer operating Reliance Smart Superstore, Reliance Digital, Trends, and Netmeds in Chhatrapati Sambhajinagar.',
    website: 'https://relianceretail.com',
    address: 'Prozone Mall, Ground Floor, API Corner, Chikalthana',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8778,
    longitude: 75.3715,
    email: 'careers.retail@ril.com',
    phone: '+91 240 6648888',
    companySize: '10,000+ employees',
    foundedYear: 2006,
    midcZone: 'Chikalthana'
  },
  {
    name: 'HDFC Bank Ltd',
    logo: 'https://logo.clearbit.com/hdfcbank.com',
    color: '#004C8F',
    industry: 'Banking & Financial Services',
    description: 'India’s premier private sector bank offering corporate loans, retail banking, MSME credit lines, wealth management, and digital banking.',
    website: 'https://www.hdfcbank.com',
    address: 'Kranti Chowk Branch, Station Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431001',
    latitude: 19.8705,
    longitude: 75.3208,
    email: 'careers.mh@hdfcbank.com',
    phone: '+91 240 2341200',
    companySize: '10,000+ employees',
    foundedYear: 1994,
    midcZone: 'Kranti Chowk'
  },
  {
    name: 'State Bank of India',
    logo: 'https://logo.clearbit.com/sbi.co.in',
    color: '#28A8E0',
    industry: 'Banking & Public Financial Institution',
    description: 'Regional administrative headquarters overseeing public banking operations, industrial finance, agricultural credit, and treasury services.',
    website: 'https://sbi.co.in',
    address: 'Zonal Office, Town Centre, CIDCO N-5',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8740,
    longitude: 75.3610,
    email: 'zo.aurangabad@sbi.co.in',
    phone: '+91 240 2485500',
    companySize: '10,000+ employees',
    foundedYear: 1955,
    midcZone: 'CIDCO N-5'
  },
  {
    name: 'MGM University',
    logo: 'https://logo.clearbit.com/mgmu.ac.in',
    color: '#1E3A8A',
    industry: 'Higher Education & Research',
    description: 'State self-financed private university offering engineering, architecture, management, journalism, biotechnology, and basic sciences.',
    website: 'https://mgmu.ac.in',
    address: 'MGM Campus, CIDCO N-6, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8748,
    longitude: 75.3638,
    email: 'registrar@mgmu.ac.in',
    phone: '+91 240 2480490',
    companySize: '1,000-5,000 employees',
    foundedYear: 1982,
    midcZone: 'CIDCO N-6'
  },
  {
    name: 'Government College of Engineering (GECA)',
    logo: 'https://logo.clearbit.com/geca.ac.in',
    color: '#B91C1C',
    industry: 'Autonomous Technical Education',
    description: 'Premier government autonomous engineering institute offering B.Tech, M.Tech, and Ph.D. degrees in mechanical, electrical, CSE, and civil.',
    website: 'https://www.geca.ac.in',
    address: 'Station Road, Osmanpura',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431005',
    latitude: 19.8680,
    longitude: 75.3245,
    email: 'principal@geca.ac.in',
    phone: '+91 240 2366101',
    companySize: '500-1,000 employees',
    foundedYear: 1960,
    midcZone: 'Osmanpura'
  },
  {
    name: 'BAMU University',
    logo: 'https://logo.clearbit.com/bamu.ac.in',
    color: '#065F46',
    industry: 'Public State University',
    description: 'Dr. Babasaheb Ambedkar Marathwada University catering to higher education, research, and affiliated colleges across Marathwada region.',
    website: 'http://www.bamu.ac.in',
    address: 'University Campus, Near Soneri Mahal',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431004',
    latitude: 19.8980,
    longitude: 75.3150,
    email: 'registrar@bamu.ac.in',
    phone: '+91 240 2403399',
    companySize: '1,000-5,000 employees',
    foundedYear: 1958,
    midcZone: 'University Campus'
  },
  {
    name: 'VRL Logistics Ltd',
    logo: 'https://logo.clearbit.com/vrlgroup.in',
    color: '#EA580C',
    industry: 'Logistics & Goods Transport',
    description: 'Pan-India goods transport, parcel delivery, cold chain logistics, and warehousing operator in Waluj hub.',
    website: 'https://www.vrlgroup.in',
    address: 'Plot No. 45, Transportation Zone, Waluj MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431136',
    latitude: 19.8440,
    longitude: 75.2360,
    email: 'aurangabad@vrlgroup.in',
    phone: '+91 240 2551900',
    companySize: '5,000-10,000 employees',
    foundedYear: 1976,
    midcZone: 'Waluj MIDC'
  },
  {
    name: 'Mahindra Logistics Ltd',
    logo: 'https://logo.clearbit.com/mahindralogistics.com',
    color: '#E11D48',
    industry: '3PL Logistics & Supply Chain',
    description: 'Third-party logistics provider managing integrated supply chain solutions, fulfillment hubs, and freight forwarding in AURIC City.',
    website: 'https://mahindralogistics.com',
    address: 'Plot No. C-4, AURIC Industrial City, Shendra',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431154',
    latitude: 19.8685,
    longitude: 75.5285,
    email: 'careers@mahindralogistics.com',
    phone: '+91 240 6654321',
    companySize: '5,000-10,000 employees',
    foundedYear: 2007,
    midcZone: 'AURIC Shendra'
  },
  {
    name: 'Welcomhotel by ITC (Rama International)',
    logo: 'https://logo.clearbit.com/itchotels.com',
    color: '#D97706',
    industry: 'Hospitality & Luxury Hotels',
    description: '5-star luxury hotel set in 13 acres of landscaped gardens, hosting corporate conventions, international tourists, and banquets.',
    website: 'https://www.itchotels.com',
    address: 'R-3, Chikalthana, Jalna Road',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8772,
    longitude: 75.3650,
    email: 'welcomhotel.ramainternational@itchotels.in',
    phone: '+91 240 6634141',
    companySize: '200-500 employees',
    foundedYear: 1975,
    midcZone: 'Chikalthana'
  },
  {
    name: 'Ambassador Ajanta Hotel',
    logo: 'https://logo.clearbit.com/ambassadorhotels.in',
    color: '#4338CA',
    industry: 'Hospitality',
    description: 'Heritage 5-star hotel offering fine dining, luxury suites, international conference facilities, and outdoor event lawns.',
    website: 'https://www.ambassadorhotels.in',
    address: 'Jalna Road, Near CIDCO Bus Stand',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8765,
    longitude: 75.3600,
    email: 'ajanta@ambassadorhotels.in',
    phone: '+91 240 2485211',
    companySize: '200-500 employees',
    foundedYear: 1978,
    midcZone: 'CIDCO'
  },
  {
    name: 'Prozone Mall',
    logo: 'https://logo.clearbit.com/prozoneintu.com',
    color: '#7E22CE',
    industry: 'Commercial Real Estate & Shopping Center',
    description: 'One of India’s largest horizontally designed shopping malls featuring INOX multiplex, international fashion brands, and food court.',
    website: 'https://www.prozoneintu.com',
    address: 'API Corner, Jalna Road, Chikalthana',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8780,
    longitude: 75.3710,
    email: 'info@prozoneintu.com',
    phone: '+91 240 6649999',
    companySize: '200-500 employees',
    foundedYear: 2010,
    midcZone: 'Chikalthana'
  },
  {
    name: 'ICICI Bank Regional Office',
    logo: 'https://logo.clearbit.com/icicibank.com',
    color: '#C2410C',
    industry: 'Banking & Financial Services',
    description: 'Regional administrative office overseeing commercial lending, industrial working capital, agri-loans, and retail banking.',
    website: 'https://www.icicibank.com',
    address: 'Plot No. 5, Jalna Road, Near Seven Hills',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431003',
    latitude: 19.8745,
    longitude: 75.3480,
    email: 'careers@icicibank.com',
    phone: '+91 240 2348800',
    companySize: '10,000+ employees',
    foundedYear: 1994,
    midcZone: 'Seven Hills'
  },
  {
    name: 'Infosys BPM Ltd',
    logo: 'https://logo.clearbit.com/infosys.com',
    color: '#0284C7',
    industry: 'IT Services & BPM',
    description: 'Business process management center delivering digital customer support, finance & accounting operations, and IT service desk support.',
    website: 'https://www.infosysbpm.com',
    address: 'Software Technology Park, Chikalthana MIDC',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    pincode: '431006',
    latitude: 19.8820,
    longitude: 75.3890,
    email: 'careers_bpm@infosys.com',
    phone: '+91 240 6614000',
    companySize: '10,000+ employees',
    foundedYear: 2002,
    midcZone: 'Chikalthana MIDC'
  }
];
