import { pool } from './config/database/pool';

// 20 new diverse professional jobs with Clearbit-style brand logos
const NEXT_20_JOBS = [
  {
    company: 'Infosys BPM',
    companyLogo: 'https://logo.clearbit.com/infosys.com',
    companyColor: '#007cc3',
    title: 'Business Process Analyst',
    industry: 'IT Services & Consulting',
    location: 'Magarpatta City, Pune',
    trade: 'Business Analysis',
    midcZone: 'Magarpatta IT Park',
    shiftDetails: 'General Shift (9 AM – 6 PM)',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 600000,
    salaryMax: 900000,
    openings: 30,
    filledOpenings: 8,
    status: 'APPROVED',
    description: 'Infosys BPM is hiring Business Process Analysts to streamline enterprise workflows, develop automation solutions and manage client SLAs across BFSI, Retail and Healthcare verticals.',
    responsibilities: [
      'Analyse and map end-to-end business processes using BPMN tools.',
      'Coordinate with global stakeholders to gather requirements and write BRDs.',
      'Identify automation opportunities using RPA and AI tools.',
    ],
    requirements: [
      'MBA / B.Tech with 2–5 years of BPO/BPM experience.',
      'Strong Excel, PowerPoint, and process mapping skills.',
      'Exposure to Six Sigma / Lean methodologies preferred.',
    ],
    skills: ['Business Analysis', 'BPMN', 'Excel', 'RPA', 'Six Sigma'],
    perks: ['Health Insurance ₹5L', 'Annual Bonus', 'Free Cab Facility'],
  },
  {
    company: 'Wipro Limited',
    companyLogo: 'https://logo.clearbit.com/wipro.com',
    companyColor: '#341d7e',
    title: 'SAP FICO Consultant',
    industry: 'IT Services & Consulting',
    location: 'Hinjewadi Phase 1, Pune',
    trade: 'ERP Consulting',
    midcZone: 'Hinjewadi IT Park',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 4,
    maxExperience: 8,
    salaryMin: 1000000,
    salaryMax: 1600000,
    openings: 15,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Wipro is looking for experienced SAP FICO Consultants to handle end-to-end implementations for Fortune 500 clients across the globe.',
    responsibilities: [
      'Lead SAP FICO module implementations and rollouts.',
      'Configure GL, AP, AR, Asset Accounting and Cost Center Accounting.',
      'Prepare functional specs and conduct user training.',
    ],
    requirements: [
      '4+ years SAP FICO consulting experience.',
      'Hands-on with S/4 HANA migration projects.',
      'Excellent stakeholder communication skills.',
    ],
    skills: ['SAP FICO', 'S/4 HANA', 'GL', 'AP', 'AR', 'Cost Center Accounting'],
    perks: ['Flexi Hours', 'Health Insurance ₹7L', 'Referral Bonus ₹50K'],
  },
  {
    company: 'Bajaj Finserv',
    companyLogo: 'https://logo.clearbit.com/bajajfinserv.in',
    companyColor: '#0064c8',
    title: 'Credit Risk Analyst',
    industry: 'BFSI',
    location: 'Viman Nagar, Pune',
    trade: 'Finance & Risk',
    midcZone: 'Viman Nagar Business District',
    shiftDetails: 'Day Shift (9 AM – 6 PM)',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 700000,
    salaryMax: 1200000,
    openings: 20,
    filledOpenings: 5,
    status: 'APPROVED',
    description: 'Bajaj Finserv is seeking Credit Risk Analysts to evaluate loan portfolios, perform underwriting assessments and build predictive risk models.',
    responsibilities: [
      'Assess creditworthiness using financial statements, bureau data, and scorecards.',
      'Build and validate credit scoring models using Python/R.',
      'Monitor NPAs and generate monthly risk dashboards.',
    ],
    requirements: [
      'CA / MBA Finance / Statistics graduate.',
      '2+ years in credit risk or retail lending.',
      'Proficient in Excel, SQL, and at least one statistical tool.',
    ],
    skills: ['Credit Risk', 'Python', 'SQL', 'Excel', 'Statistical Modelling'],
    perks: ['ESOP', 'Medical Cover ₹5L', 'Performance Bonus'],
  },
  {
    company: 'Mahindra Electric',
    companyLogo: 'https://logo.clearbit.com/mahindra.com',
    companyColor: '#c8102e',
    title: 'EV Battery Systems Engineer',
    industry: 'Electric Vehicles',
    location: 'Chakan MIDC Phase 3, Pune',
    trade: 'Automotive Engineering',
    midcZone: 'Chakan MIDC Phase 3',
    shiftDetails: 'General Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 8,
    salaryMin: 900000,
    salaryMax: 1400000,
    openings: 12,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Mahindra Electric is hiring EV Battery Systems Engineers to design, validate, and optimise battery packs for next-generation electric SUVs and commercial vehicles.',
    responsibilities: [
      'Design battery pack architecture and thermal management systems.',
      'Develop BMS algorithms and validate through HIL/SIL testing.',
      'Collaborate with OEM suppliers on cell selection and qualification.',
    ],
    requirements: [
      'B.E./M.Tech Electrical/Mechanical with 3+ years EV battery experience.',
      'Strong understanding of LFP/NMC cell chemistry.',
      'MATLAB/Simulink proficiency required.',
    ],
    skills: ['Battery Management System', 'MATLAB', 'Thermal Management', 'EV', 'HIL Testing'],
    perks: ['EV Vehicle Allowance', 'Joining Bonus ₹1L', 'Health Cover ₹7L'],
  },
  {
    company: 'Persistent Systems',
    companyLogo: 'https://logo.clearbit.com/persistent.com',
    companyColor: '#e31837',
    title: 'Cloud DevOps Engineer',
    industry: 'IT Software',
    location: 'Senapati Bapat Road, Pune',
    trade: 'DevOps & Cloud',
    midcZone: 'SB Road Tech Corridor',
    shiftDetails: 'General Shift / US Overlap (2 PM – 11 PM)',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 1100000,
    salaryMax: 1700000,
    openings: 18,
    filledOpenings: 4,
    status: 'APPROVED',
    description: 'Persistent Systems is looking for Cloud DevOps Engineers to build and manage scalable CI/CD pipelines, Kubernetes clusters, and cloud-native applications on AWS/Azure.',
    responsibilities: [
      'Design and manage CI/CD pipelines using Jenkins, GitLab CI, and ArgoCD.',
      'Manage Kubernetes (EKS/AKS) clusters with Helm and Terraform.',
      'Implement monitoring and alerting using Prometheus, Grafana, and Datadog.',
    ],
    requirements: [
      '3+ years DevOps/SRE experience.',
      'AWS / Azure certification preferred.',
      'Strong scripting in Python/Bash.',
    ],
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Prometheus', 'Grafana'],
    perks: ['WFH Allowance ₹20K', 'AWS Certification Support', 'Annual Bonus'],
  },
  {
    company: 'Cummins India',
    companyLogo: 'https://logo.clearbit.com/cummins.com',
    companyColor: '#e2231a',
    title: 'Engine Test & Validation Engineer',
    industry: 'Power & Industrial',
    location: 'Kothrud, Pune',
    trade: 'Mechanical Engineering',
    midcZone: 'Kothrud Industrial Area',
    shiftDetails: 'General Shift (7:30 AM – 4:30 PM)',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 700000,
    salaryMax: 1100000,
    openings: 8,
    filledOpenings: 1,
    status: 'APPROVED',
    description: 'Cummins India is looking for Engine Test & Validation Engineers to conduct performance, emissions, and durability testing of diesel and natural gas engines.',
    responsibilities: [
      'Execute engine test plans on dynamometer test cells.',
      'Analyse calibration data and create test reports.',
      'Support homologation activities for BS-VI and Euro-VI emissions norms.',
    ],
    requirements: [
      'B.E. Mechanical / Automobile with 2+ years in engine testing.',
      'Experience with AVL PUMA or similar test cell software.',
      'Knowledge of emissions standards (BS-VI, EPA, CARB).',
    ],
    skills: ['Engine Testing', 'AVL PUMA', 'Dynamometer', 'FMEA', 'BS-VI'],
    perks: ['Medical Cover ₹5L', 'Annual Increment 10%', 'Subsidized Canteen'],
  },
  {
    company: 'Zensar Technologies',
    companyLogo: 'https://logo.clearbit.com/zensar.com',
    companyColor: '#00b4d8',
    title: 'Data Engineer – Databricks & Spark',
    industry: 'IT Services',
    location: 'Kharadi, Pune',
    trade: 'Data Engineering',
    midcZone: 'Kharadi EON Free Zone',
    shiftDetails: 'General Shift / Flexible',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 1000000,
    salaryMax: 1600000,
    openings: 20,
    filledOpenings: 6,
    status: 'APPROVED',
    description: 'Zensar Technologies is hiring Data Engineers with expertise in Databricks, Apache Spark and Delta Lake to build enterprise-scale data pipelines for US retail clients.',
    responsibilities: [
      'Build and optimise ETL/ELT pipelines using Databricks and PySpark.',
      'Design Delta Lake medallion architecture (Bronze/Silver/Gold layers).',
      'Implement data quality checks using Great Expectations or Deequ.',
    ],
    requirements: [
      '3+ years data engineering experience.',
      'Hands-on with Databricks, Spark, and cloud storage (S3/ADLS).',
      'SQL expertise and experience with dbt preferred.',
    ],
    skills: ['Databricks', 'Apache Spark', 'Delta Lake', 'PySpark', 'SQL', 'dbt'],
    perks: ['Remote Flexibility', 'Annual Bonus 15%', 'Certification Budget ₹30K'],
  },
  {
    company: 'Volkswagen India',
    companyLogo: 'https://logo.clearbit.com/volkswagen.co.in',
    companyColor: '#001e50',
    title: 'Plastic Injection Moulding Technician',
    industry: 'Automotive Manufacturing',
    location: 'Chakan, Pune',
    trade: 'Tool & Die',
    midcZone: 'Chakan MIDC',
    shiftDetails: 'Rotating Shift (A/B)',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 7,
    salaryMin: 360000,
    salaryMax: 540000,
    openings: 40,
    filledOpenings: 12,
    status: 'APPROVED',
    description: 'Volkswagen India (Pune Plant) is recruiting Plastic Injection Moulding Technicians for automotive interior and exterior component production.',
    responsibilities: [
      'Set up and operate injection moulding machines (200T–2000T).',
      'Perform first-article inspection and SPC monitoring.',
      'Carry out preventive maintenance and troubleshoot mould defects.',
    ],
    requirements: [
      'ITI Plastics / Mechanical or Diploma holder.',
      '2+ years moulding experience in automotive Tier-1 supplier.',
      'Knowledge of hot runner systems and colour change procedures.',
    ],
    skills: ['Injection Moulding', 'SPC', 'Hot Runner', 'Automotive Plastics', 'QC'],
    perks: ['OT Pay 2x', 'Attendance Bonus ₹2,500', 'Free Accommodation', 'Bus Facility'],
  },
  {
    company: 'KPIT Technologies',
    companyLogo: 'https://logo.clearbit.com/kpit.com',
    companyColor: '#005aab',
    title: 'AUTOSAR Software Engineer',
    industry: 'Automotive Software',
    location: 'Hinjewadi Phase 2, Pune',
    trade: 'Embedded Systems',
    midcZone: 'Hinjewadi Phase 2',
    shiftDetails: 'General Shift (9 AM – 6 PM)',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 8,
    salaryMin: 1000000,
    salaryMax: 1500000,
    openings: 25,
    filledOpenings: 7,
    status: 'APPROVED',
    description: 'KPIT Technologies is hiring AUTOSAR Software Engineers to develop and integrate BSW/ASW components for next-generation ECUs across powertrain and ADAS domains.',
    responsibilities: [
      'Develop and configure AUTOSAR BSW components using Vector DaVinci.',
      'Integrate and test ASW components on target ECUs.',
      'Perform static code analysis using MISRA C and Polyspace.',
    ],
    requirements: [
      'B.E. Electronics / Computer Engineering.',
      '3+ years AUTOSAR Classic or Adaptive experience.',
      'Hands-on with Vector toolchain (CANoe, DaVinci Configurator, CANdb++).',
    ],
    skills: ['AUTOSAR', 'Embedded C', 'Vector CANoe', 'MISRA C', 'ECU Testing'],
    perks: ['Joining Bonus ₹75K', 'Flexible Hours', 'EV Project Exposure'],
  },
  {
    company: 'Thermax Limited',
    companyLogo: 'https://logo.clearbit.com/thermax.com',
    companyColor: '#e2211b',
    title: 'Senior Process Design Engineer',
    industry: 'Energy & Environment',
    location: 'Chinchwad, Pune',
    trade: 'Chemical Engineering',
    midcZone: 'Chinchwad MIDC',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 5,
    maxExperience: 10,
    salaryMin: 1200000,
    salaryMax: 1800000,
    openings: 6,
    filledOpenings: 1,
    status: 'APPROVED',
    description: 'Thermax Limited is looking for Senior Process Design Engineers to develop waste heat recovery, biomass, and industrial boiler systems for global EPC projects.',
    responsibilities: [
      'Prepare PFDs, P&IDs, heat and mass balances for boiler/WHR projects.',
      'Size equipment including heat exchangers, evaporators, and fans.',
      'Interface with mechanical, electrical, and instrumentation teams.',
    ],
    requirements: [
      'B.E. / M.E. Chemical Engineering with 5+ years EPC experience.',
      'Proficiency in ASPEN Plus / HYSYS and AutoCAD P&ID.',
      'Knowledge of PED, ASME standards.',
    ],
    skills: ['Process Design', 'ASPEN Plus', 'HYSYS', 'P&ID', 'Heat Exchanger'],
    perks: ['Global Project Exposure', 'Flexi Leave Policy', 'Medical Cover ₹5L'],
  },
  {
    company: 'Tech Mahindra',
    companyLogo: 'https://logo.clearbit.com/techmahindra.com',
    companyColor: '#c11d2e',
    title: 'Python Backend Developer – FastAPI',
    industry: 'IT Software',
    location: 'Viman Nagar, Pune',
    trade: 'Backend Development',
    midcZone: 'Viman Nagar',
    shiftDetails: 'General Shift / US Overlap',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 950000,
    salaryMax: 1400000,
    openings: 22,
    filledOpenings: 5,
    status: 'APPROVED',
    description: 'Tech Mahindra is hiring Python Backend Developers with FastAPI experience to build high-throughput REST APIs and microservices for telecom and media clients.',
    responsibilities: [
      'Design and develop RESTful APIs using FastAPI and SQLAlchemy.',
      'Implement authentication with OAuth2 / JWT and rate limiting.',
      'Optimise PostgreSQL queries and manage database migrations with Alembic.',
    ],
    requirements: [
      '3+ years Python backend development.',
      'Strong FastAPI / Django REST Framework experience.',
      'Good understanding of async programming, Redis caching.',
    ],
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'JWT'],
    perks: ['WFH Flexibility', 'Annual Bonus', 'Health Insurance ₹5L'],
  },
  {
    company: 'Bosch Rexroth India',
    companyLogo: 'https://logo.clearbit.com/boschrexroth.com',
    companyColor: '#e20015',
    title: 'Hydraulic Design Engineer',
    industry: 'Industrial Automation',
    location: 'Pimpri, Pune',
    trade: 'Mechanical Engineering',
    midcZone: 'Pimpri-Chinchwad MIDC',
    shiftDetails: 'General Shift (8 AM – 5 PM)',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 4,
    maxExperience: 8,
    salaryMin: 900000,
    salaryMax: 1400000,
    openings: 10,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Bosch Rexroth India is seeking Hydraulic Design Engineers to develop and validate hydraulic systems and circuits for industrial presses, injection moulding, and mobile machinery.',
    responsibilities: [
      'Design hydraulic circuits using Bosch Rexroth components and HACD software.',
      'Create 3D models and drawings using CATIA V5 or SolidWorks.',
      'Validate systems through test rigs and field commissioning.',
    ],
    requirements: [
      'B.E. / Diploma Mechanical with 4+ years hydraulics experience.',
      'Hands-on with proportional/servo valves and PLC integration.',
      'Familiarity with Parker, Bosch, or Eaton product lines.',
    ],
    skills: ['Hydraulics', 'CATIA V5', 'PLC', 'SolidWorks', 'Hydraulic Circuits'],
    perks: ['Annual Increment 12%', 'Global Training Opportunities', 'Subsidized Canteen'],
  },
  {
    company: 'Accenture',
    companyLogo: 'https://logo.clearbit.com/accenture.com',
    companyColor: '#a100ff',
    title: 'Salesforce CRM Developer',
    industry: 'IT Consulting',
    location: 'Baner, Pune',
    trade: 'CRM Development',
    midcZone: 'Baner-Balewadi Corridor',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 1100000,
    salaryMax: 1700000,
    openings: 28,
    filledOpenings: 9,
    status: 'APPROVED',
    description: 'Accenture is looking for Salesforce CRM Developers to build and enhance Sales Cloud, Service Cloud, and CPQ solutions for Fortune 500 clients.',
    responsibilities: [
      'Develop custom Apex classes, triggers, LWC components, and Visualforce pages.',
      'Design and implement Salesforce CPQ pricing and product rules.',
      'Integrate Salesforce with ERP systems using REST/SOAP APIs.',
    ],
    requirements: [
      'Salesforce Developer / Administrator certification required.',
      '3+ years Salesforce development experience.',
      'Experience with Salesforce CPQ and Einstein Analytics a plus.',
    ],
    skills: ['Salesforce', 'Apex', 'LWC', 'CPQ', 'REST API', 'Integration'],
    perks: ['Certification Reimbursement', 'Joining Bonus ₹1L', 'Flexi Benefits'],
  },
  {
    company: 'Tata Motors',
    companyLogo: 'https://logo.clearbit.com/tatamotors.com',
    companyColor: '#00529b',
    title: 'Sheet Metal Press Shop Supervisor',
    industry: 'Automotive Manufacturing',
    location: 'Pimpri, Pune',
    trade: 'Press Shop',
    midcZone: 'PCMC Industrial Area',
    shiftDetails: 'Rotating Shift (A/B/C)',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 4,
    maxExperience: 10,
    salaryMin: 480000,
    salaryMax: 720000,
    openings: 15,
    filledOpenings: 4,
    status: 'APPROVED',
    description: 'Tata Motors is hiring Press Shop Supervisors to manage stamping operations, die setting, and in-process quality control for body panels of commercial and passenger vehicles.',
    responsibilities: [
      'Supervise press shop stamping operations (200T–1600T presses).',
      'Coordinate die changes and ensure production targets are met.',
      'Lead a team of 15–20 operators and conduct daily shift briefings.',
    ],
    requirements: [
      'Diploma / ITI Mechanical or Tool & Die with 4+ years press shop experience.',
      'Expertise in die setting, progressive die, and blanking operations.',
      'Knowledge of PFMEA and Control Plans.',
    ],
    skills: ['Press Shop', 'Sheet Metal Stamping', 'Die Setting', 'PFMEA', 'QC'],
    perks: ['OT Pay 2x', 'Attendance Bonus ₹2,000/month', 'Bus Facility'],
  },
  {
    company: 'Amazon India',
    companyLogo: 'https://logo.clearbit.com/amazon.in',
    companyColor: '#ff9900',
    title: 'Operations Manager – Fulfillment Center',
    industry: 'E-commerce & Logistics',
    location: 'Talegaon Dabhade, Pune',
    trade: 'Warehouse Operations',
    midcZone: 'Talegaon MIDC',
    shiftDetails: 'Day Shift / Night Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 8,
    salaryMin: 900000,
    salaryMax: 1500000,
    openings: 10,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Amazon India is hiring Operations Managers for its Talegaon Fulfillment Center to drive productivity metrics, safety compliance, and team management across inbound, pick, pack, and ship operations.',
    responsibilities: [
      'Manage 100+ associates across multiple operational areas.',
      'Monitor and report shift-wise productivity and quality KPIs.',
      'Drive Kaizen events and implement process improvement initiatives.',
    ],
    requirements: [
      'MBA Operations / B.Tech with 3+ years warehouse/logistics management.',
      'Experience in high-volume e-commerce or FMCG operations.',
      'Strong analytical skills; proficiency in Excel and WMS systems.',
    ],
    skills: ['Warehouse Management', 'WMS', 'Kaizen', 'Operations', 'Team Leadership'],
    perks: ['ESOPs', 'Annual Performance Bonus', 'Health Insurance ₹7L', 'Cab Facility'],
  },
  {
    company: 'Bharat Forge',
    companyLogo: 'https://logo.clearbit.com/bharatforge.com',
    companyColor: '#003087',
    title: 'CNC Machining Centre Operator – Aerospace',
    industry: 'Aerospace & Defence',
    location: 'Mundhwa, Pune',
    trade: 'CNC Machining',
    midcZone: 'Mundhwa Industrial Area',
    shiftDetails: 'Rotating Shift (A/B)',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 8,
    salaryMin: 420000,
    salaryMax: 660000,
    openings: 18,
    filledOpenings: 5,
    status: 'APPROVED',
    description: 'Bharat Forge is hiring CNC Machining Centre Operators for precision aerospace component machining to AS9100D quality standards.',
    responsibilities: [
      'Operate 4/5-axis VMC/HMC machines for aerospace-grade titanium and Inconel components.',
      'Set up and prove-out machining programs using Siemens/Fanuc controllers.',
      'Perform in-process inspection using CMM and precision gauging.',
    ],
    requirements: [
      'ITI / Diploma Machinist with 3+ years CNC VMC/HMC operation.',
      'Experience in aerospace or defence machining preferred.',
      'Knowledge of GD&T and AS9100D standards.',
    ],
    skills: ['CNC Machining', '4-axis VMC', 'CMM', 'GD&T', 'AS9100D', 'FANUC'],
    perks: ['Joining Bonus ₹50K', 'OT Allowance', 'Attendance Bonus ₹1,500'],
  },
  {
    company: 'Capgemini',
    companyLogo: 'https://logo.clearbit.com/capgemini.com',
    companyColor: '#0070ad',
    title: 'Angular Frontend Developer',
    industry: 'IT Services',
    location: 'Pune University Road',
    trade: 'Frontend Development',
    midcZone: 'University Road IT Belt',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 700000,
    salaryMax: 1100000,
    openings: 35,
    filledOpenings: 10,
    status: 'APPROVED',
    description: 'Capgemini is looking for Angular Frontend Developers to build enterprise-grade web applications for banking, insurance, and retail clients across Europe and North America.',
    responsibilities: [
      'Develop responsive, accessible Angular 16+ SPA applications.',
      'Implement NgRx state management and RxJS-driven data flows.',
      'Write unit tests with Jasmine/Karma and integration tests with Cypress.',
    ],
    requirements: [
      '2+ years Angular development experience.',
      'Proficient in TypeScript, SCSS, and REST API integration.',
      'Experience with Storybook and design system implementation a plus.',
    ],
    skills: ['Angular', 'TypeScript', 'NgRx', 'RxJS', 'SCSS', 'Cypress'],
    perks: ['Annual Bonus', 'Certification Budget ₹25K', 'Hybrid Work Policy'],
  },
  {
    company: 'Godrej & Boyce',
    companyLogo: 'https://logo.clearbit.com/godrej.com',
    companyColor: '#003466',
    title: 'PLC & SCADA Automation Engineer',
    industry: 'Industrial Automation',
    location: 'Bhosari MIDC, Pune',
    trade: 'Electrical Automation',
    midcZone: 'Bhosari MIDC',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 8,
    salaryMin: 600000,
    salaryMax: 960000,
    openings: 12,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Godrej & Boyce is hiring PLC & SCADA Automation Engineers to design, commission, and maintain automated manufacturing lines in the storage solutions and precision engineering division.',
    responsibilities: [
      'Program and troubleshoot Siemens S7-300/400/1500 and Allen-Bradley PLCs.',
      'Develop and maintain SCADA HMI applications (Wonderware/iFIX).',
      'Commission automated assembly lines and robot integrations.',
    ],
    requirements: [
      'B.E. Electrical / Electronics with 3+ years PLC/SCADA experience.',
      'Hands-on with Siemens TIA Portal and AB Studio 5000.',
      'Knowledge of industrial networks: Profibus, Profinet, EtherNet/IP.',
    ],
    skills: ['PLC', 'SCADA', 'Siemens S7', 'Allen-Bradley', 'Profinet', 'HMI'],
    perks: ['Attendance Bonus ₹1,000', 'Flexi Leave Policy', 'Subsidized Meals'],
  },
  {
    company: 'Bajaj Auto',
    companyLogo: 'https://logo.clearbit.com/bajajauto.com',
    companyColor: '#1a5276',
    title: 'Two-Wheeler Paint Shop Lead',
    industry: 'Automotive Manufacturing',
    location: 'Akurdi, Pune',
    trade: 'Paint Shop',
    midcZone: 'Akurdi Plant',
    shiftDetails: 'Rotating Shift (A/B)',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 4,
    maxExperience: 9,
    salaryMin: 500000,
    salaryMax: 760000,
    openings: 8,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Bajaj Auto is seeking a Two-Wheeler Paint Shop Lead to manage pre-treatment, e-coat, top coat, and final inspection operations at the Akurdi manufacturing plant.',
    responsibilities: [
      'Lead paint shop operations (Pre-treatment, E-coat, Base coat, Clear coat).',
      'Maintain colour shade standards and DFT measurements.',
      'Implement 5S and Kaizen activities to improve paint defect rates.',
    ],
    requirements: [
      'Diploma / B.E. Mechanical or Paint Technology with 4+ years automotive paint shop experience.',
      'Knowledge of CED process, paint application robotics, and colour management.',
      'Experience in ISO 9001 and IATF 16949 environments.',
    ],
    skills: ['Paint Shop', 'E-coat', 'CED Process', 'IATF 16949', '5S', 'Kaizen'],
    perks: ['OT Pay 2x', 'Bus Facility', 'Attendance Bonus ₹1,800/month'],
  },
  {
    company: 'Cognizant',
    companyLogo: 'https://logo.clearbit.com/cognizant.com',
    companyColor: '#1a2e6c',
    title: 'QA Automation Engineer – Selenium & Playwright',
    industry: 'IT Services',
    location: 'Hinjewadi Phase 1, Pune',
    trade: 'Quality Assurance',
    midcZone: 'Hinjewadi IT Park',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 700000,
    salaryMax: 1100000,
    openings: 40,
    filledOpenings: 12,
    status: 'APPROVED',
    description: 'Cognizant is hiring QA Automation Engineers to build end-to-end test suites using Selenium, Playwright, and Cucumber for healthcare and insurance clients.',
    responsibilities: [
      'Design and maintain automated test frameworks using Selenium WebDriver + TestNG.',
      'Develop Playwright/TypeScript scripts for cross-browser E2E testing.',
      'Integrate test suites into Jenkins/GitLab CI/CD pipelines.',
    ],
    requirements: [
      '2+ years test automation experience.',
      'Strong Java or Python scripting for Selenium tests.',
      'Experience with API testing tools (Postman, RestAssured).',
    ],
    skills: ['Selenium', 'Playwright', 'Cucumber', 'TestNG', 'Jenkins', 'RestAssured'],
    perks: ['WFH Days', 'Joining Bonus ₹75K', 'Health Insurance ₹5L'],
  },
];

async function seedNext20Jobs() {
  console.log('🚀 Seeding 20 New Professional Jobs with Clearbit Brand Logos...');

  try {
    let employerRes = await pool.query("SELECT id FROM users WHERE role = 'EMPLOYER' LIMIT 1;");
    let employerId = employerRes.rows[0]?.id;

    if (!employerId) {
      const newEmployer = await pool.query(`
        INSERT INTO users (email, password_hash, name, phone, role, company_name, status)
        VALUES ('recruiter.next20@jobmarket.com', '$2b$10$X7WzD.4.O7gD7qMv/xW6U.rN81lKzP3eZ1zQZ.X61W2Z3Y4X5Y6Z7', 'Premium Recruiter', '9876543210', 'EMPLOYER', 'Premium Enterprises Pvt Ltd', 'APPROVED')
        RETURNING id;
      `);
      employerId = newEmployer.rows[0].id;
    }

    const query = `
      INSERT INTO jobs (
        employer_id, company, company_logo, company_color, title, industry, location,
        trade, midc_zone, shift_details, overtime, accommodation, bus_facility, canteen,
        joining_bonus, attendance_bonus, contract_duration, job_type, work_mode,
        min_experience, max_experience, salary_min, salary_max, openings, filled_openings,
        status, description, responsibilities, requirements, skills, perks, posted_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
        $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, NOW() - ($32 || ' hours')::INTERVAL
      );
    `;

    let count = 0;
    for (const job of NEXT_20_JOBS) {
      const values = [
        employerId,
        job.company,
        job.companyLogo,
        job.companyColor,
        job.title,
        job.industry,
        job.location,
        job.trade,
        job.midcZone,
        job.shiftDetails,
        job.overtime,
        job.accommodation,
        job.busFacility,
        job.canteen,
        job.joiningBonus,
        job.attendanceBonus,
        job.contractDuration,
        job.jobType,
        job.workMode,
        job.minExperience,
        job.maxExperience,
        job.salaryMin,
        job.salaryMax,
        job.openings,
        job.filledOpenings,
        job.status,
        job.description,
        JSON.stringify(job.responsibilities),
        JSON.stringify(job.requirements),
        JSON.stringify(job.skills),
        JSON.stringify(job.perks),
        (count * 3).toString(),
      ];

      await pool.query(query, values);
      count++;
      console.log(`[${count}/20] ✅ "${job.title}" @ ${job.company}`);
    }

    console.log('🎉 20 professional jobs with Clearbit logos inserted successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Error seeding next 20 jobs:', err);
    process.exit(1);
  }
}

seedNext20Jobs();
