import { pool } from './config/database/pool';

const ADDITIONAL_20_JOBS = [
  {
    company: 'Tata Consultancy Services',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0052cc',
    title: 'Java FSD with React and AWS',
    industry: 'IT Services & Consulting',
    location: 'Hinjewadi Phase 3, Pune',
    trade: 'Software Engineering',
    midcZone: 'Hinjewadi Phase 3',
    shiftDetails: 'General Shift (9:00 AM - 6:00 PM)',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 5,
    maxExperience: 10,
    salaryMin: 1200000,
    salaryMax: 1800000,
    openings: 25,
    filledOpenings: 5,
    status: 'APPROVED',
    description: 'Urgent requirement for Senior Java Full Stack Developers with proficiency in React.js, Spring Boot, Microservices, and AWS Cloud deployments.',
    responsibilities: [
      'Design, develop, and maintain high-performance Java microservices.',
      'Build responsive front-end interfaces using React and Redux.',
      'Deploy applications on AWS ECS/EKS with CI/CD pipelines.'
    ],
    requirements: [
      'B.Tech / MCA in Computer Science or related field.',
      '5+ years experience in Java 17+, Spring Boot, and React.',
      'Strong knowledge of AWS services (S3, Lambda, RDS).'
    ],
    skills: ['Java', 'Spring Boot', 'React', 'AWS', 'Microservices'],
    perks: ['Health Insurance ₹5L', 'WFH Allowance', 'Annual Performance Bonus']
  },
  {
    company: 'Creospan Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#f59e0b',
    title: 'Java Fullstack Engineer',
    industry: 'IT Software',
    location: 'Kharadi, Pune',
    trade: 'Software Engineering',
    midcZone: 'Kharadi IT Park',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 8,
    maxExperience: 12,
    salaryMin: 3000000,
    salaryMax: 3500000,
    openings: 10,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Looking for Lead Full Stack Developers to architect enterprise web solutions for US clients. High growth potential.',
    responsibilities: [
      'Architect scalable full-stack applications.',
      'Lead a team of 6 engineers and perform code reviews.',
      'Collaborate with product managers on feature roadmaps.'
    ],
    requirements: [
      '8+ years full stack development experience.',
      'Mastery in Java, Angular/React, PostgreSQL.',
      'Excellent client communication skills.'
    ],
    skills: ['Java', 'Full Stack', 'PostgreSQL', 'System Design', 'React'],
    perks: ['Competitive CTC', 'Flexible Work Hours', 'Medical Cover']
  },
  {
    company: 'Persistent Systems',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#ea580c',
    title: 'Agile Scrum Master',
    industry: 'IT & Product Development',
    location: 'Senapati Bapat Road, Pune',
    trade: 'Project Management',
    midcZone: 'SB Road',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    minExperience: 10,
    maxExperience: 16,
    salaryMin: 2200000,
    salaryMax: 2800000,
    openings: 6,
    filledOpenings: 1,
    status: 'APPROVED',
    description: 'Hiring certified Scrum Masters to facilitate Agile practices across multiple cross-functional software delivery squads.',
    responsibilities: [
      'Facilitate daily standups, sprint planning, and retrospectives.',
      'Remove blockers and optimize team velocity.',
      'Guide product owners on backlog refinement.'
    ],
    requirements: [
      'Certified Scrum Master (CSM / PSM I).',
      '10+ years in IT with 4+ years as a Scrum Master.',
      'Proficiency with Jira, Confluence, and Agile metrics.'
    ],
    skills: ['Scrum', 'Agile', 'Jira', 'Sprint Planning', 'Kanban'],
    perks: ['Certification Reimbursement', 'Parental Health Insurance']
  },
  {
    company: 'JAV Consultancy Services',
    companyLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#dc2626',
    title: 'Staff Software Engineer - Backend',
    industry: 'Recruitment & Staffing',
    location: 'Magarpatta City, Pune',
    trade: 'Software Engineering',
    midcZone: 'Magarpatta Cybercity',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: false,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 8,
    maxExperience: 14,
    salaryMin: 4000000,
    salaryMax: 4200000,
    openings: 4,
    filledOpenings: 0,
    status: 'APPROVED',
    description: 'Hiring Staff Engineers to build resilient high-throughput backend services and data streaming pipelines.',
    responsibilities: [
      'Design distributed systems handling millions of daily requests.',
      'Optimize database performance and Redis caching layers.',
      'Mentor senior and mid-level software engineers.'
    ],
    requirements: [
      '8+ years backend engineering experience.',
      'Expertise in Node.js / Go / Java and distributed databases.',
      'Experience with Kafka / RabbitMQ messaging queues.'
    ],
    skills: ['Node.js', 'Go', 'Kafka', 'System Architecture', 'Redis'],
    perks: ['Stock Options (ESOPs)', 'Unlimited Casual Leave']
  },
  {
    company: 'Bajaj Auto Limited',
    companyLogo: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0284c7',
    title: 'EV Assembly Line Quality Supervisor',
    industry: 'Automobile Manufacturing',
    location: 'Akurdi, Pune',
    trade: 'Electrical / Automobile',
    midcZone: 'Akurdi Industrial Belt',
    shiftDetails: '1st Shift (7:30 AM - 4:00 PM)',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 6,
    salaryMin: 35000,
    salaryMax: 45000,
    openings: 12,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Quality Supervisor required for Electric Vehicle (Chetak EV) battery assembly and motor integration line.',
    responsibilities: [
      'Oversee battery pack voltage testing and harness fitment.',
      'Ensure zero defect rate on final vehicle assembly line.',
      'Train line operators on EV safety standard operating procedures.'
    ],
    requirements: [
      'Diploma or BE in Electrical / Mechanical Engineering.',
      '3+ years experience in EV or automotive quality control.',
      'Knowledge of Lithium-ion battery BMS safety protocols.'
    ],
    skills: ['EV Battery', 'Quality Control', 'BMS Testing', 'Assembly Line', 'IATF 16949'],
    perks: ['Company Vehicle Subsidy', 'Overtime Pay', 'Free Bus & Canteen']
  },
  {
    company: 'Cummins India Heavy Diesel',
    companyLogo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#b91c1c',
    title: 'Heavy Diesel Engine Maintenance Fitter',
    industry: 'Heavy Machinery & Generators',
    location: 'Phaltan MIDC / Kothrud, Pune',
    trade: 'Fitter / Diesel Mechanic',
    midcZone: 'Phaltan MIDC',
    shiftDetails: 'Rotational Shifts',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 24000,
    salaryMax: 32000,
    openings: 20,
    filledOpenings: 8,
    status: 'APPROVED',
    description: 'Maintenance fitters needed for testing and assembly of high-horsepower industrial diesel generator engines.',
    responsibilities: [
      'Assemble fuel injection pumps, turbochargers, and pistons.',
      'Conduct engine dynamometer testing and load trials.',
      'Perform preventive maintenance on plant machinery.'
    ],
    requirements: [
      'ITI Diesel Mechanic or Fitter.',
      '2+ years experience in heavy engine overhauling.',
      'Ability to read pneumatic & hydraulic circuit diagrams.'
    ],
    skills: ['Diesel Engine', 'Overhauling', 'Dynamometer', 'Pneumatics', 'Fitter'],
    perks: ['Shift Allowance ₹250/day', 'Group Mediclaim ₹4L']
  },
  {
    company: 'Siemens Industrial Automation',
    companyLogo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0d9488',
    title: 'PLC & SCADA Automation Engineer',
    industry: 'Industrial Automation',
    location: 'Kalwa / Pimpri MIDC, Pune',
    trade: 'Instrumentation / Electrical',
    midcZone: 'Pimpri MIDC',
    shiftDetails: 'General Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 45000,
    salaryMax: 65000,
    openings: 8,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Hiring automation engineers for programming S7-1200 / S7-1500 PLCs and WinCC SCADA systems for factory automation.',
    responsibilities: [
      'Develop TIA Portal PLC logic and HMI screens.',
      'Commission automated conveyor lines at client factory sites.',
      'Troubleshoot Fieldbus, PROFINET, and industrial sensor networks.'
    ],
    requirements: [
      'BE / Diploma in Instrumentation / Electrical Engineering.',
      '3+ years hands-on experience with Siemens PLC programming.',
      'Willingness to travel for field commissioning.'
    ],
    skills: ['PLC', 'SCADA', 'TIA Portal', 'Siemens S7', 'PROFINET'],
    perks: ['Travel Allowance', 'Site Commissioning Bonus', 'Health Insurance']
  },
  {
    company: 'SKF Bearings India',
    companyLogo: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#1e40af',
    title: 'Tool & Die Maker (Grinding & Heat Treatment)',
    industry: 'Precision Mechanical Engineering',
    location: 'Chinchwad MIDC, Pune',
    trade: 'Tool & Die Maker',
    midcZone: 'Chinchwad MIDC',
    shiftDetails: '1st & 2nd Rotational Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 4,
    maxExperience: 8,
    salaryMin: 28000,
    salaryMax: 36000,
    openings: 10,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Looking for skilled Tool & Die Makers for precision bearing race grinding, press tool maintenance, and die setting.',
    responsibilities: [
      'Manufacture and repair press tools, jigs, and fixtures.',
      'Operate surface grinders and cylindrical grinding machines.',
      'Maintain sub-micron dimensional tolerances on bearing rings.'
    ],
    requirements: [
      'ITI Tool & Die Maker or NTTF / IGTR Diploma.',
      '4+ years in precision press tool shop.',
      'Proficiency in using precision gauge blocks & dial indicators.'
    ],
    skills: ['Tool & Die', 'Grinding', 'Jigs & Fixtures', 'Press Tools', 'Micron Tolerance'],
    perks: ['Quarterly Productivity Bonus', 'Subsidized Canteen']
  },
  {
    company: 'Kirloskar Oil Engines Ltd',
    companyLogo: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#059669',
    title: 'Foundry Pattern Maker & Casting Inspector',
    industry: 'Foundry & Metallurgy',
    location: 'Kagal MIDC / Hadapsar, Pune',
    trade: 'Pattern Maker / Foundryman',
    midcZone: 'Hadapsar Industrial Zone',
    shiftDetails: '1st Shift (8:00 AM - 4:30 PM)',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 23000,
    salaryMax: 31000,
    openings: 14,
    filledOpenings: 5,
    status: 'APPROVED',
    description: 'Pattern makers needed for wooden & aluminum foundry pattern development, sand mold inspection, and casting defect analysis.',
    responsibilities: [
      'Fabricate wooden and metallic foundry patterns based on 2D drawings.',
      'Inspect sand molds for hardness, moisture, and core alignment.',
      'Identify casting defects (blowholes, shrinkage) and suggest gating fixes.'
    ],
    requirements: [
      'ITI Pattern Maker or Foundryman.',
      '2+ years in gray iron / ductile iron foundry.',
      'Good understanding of mold gating and riser systems.'
    ],
    skills: ['Foundry', 'Pattern Making', 'Casting Inspection', 'Sand Molding', 'Metallurgy'],
    perks: ['Foundry Safety Allowance', 'Free Milk & Snacks']
  },
  {
    company: 'Bharat Forge Limited',
    companyLogo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#4338ca',
    title: 'Drop Forge Hammer Press Operator',
    industry: 'Forging & Aerospace Components',
    location: 'Mundhwa, Pune',
    trade: 'Forging Operator / Blacksmith',
    midcZone: 'Mundhwa Industrial Area',
    shiftDetails: 'Rotational 3 Shifts',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 9,
    salaryMin: 30000,
    salaryMax: 42000,
    openings: 18,
    filledOpenings: 6,
    status: 'APPROVED',
    description: 'Hiring press operators for closed-die forging of crankshafts, axle beams, and heavy aerospace forgings.',
    responsibilities: [
      'Operate 5-ton to 16-ton forging hammers and hydraulic presses.',
      'Monitor billet induction heating temperatures (1200°C).',
      'Perform hot dimension checks using forging calipers.'
    ],
    requirements: [
      'ITI Forging / Heat Treatment or 3+ years heavy forging experience.',
      'Physical fitness to work in high-temperature forge shop environment.',
      'Strict adherence to heat safety gear protocols.'
    ],
    skills: ['Forging', 'Hydraulic Press', 'Induction Heating', 'Hot Dimensional Check', 'Heat Treatment'],
    perks: ['High Heat Hazard Incentive', 'Free Nutritional Meals']
  },
  {
    company: 'L&T Defense & Heavy Engineering',
    companyLogo: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#1e3a8a',
    title: 'CNC Heavy Horizontal Boring Operator',
    industry: 'Defense & Shipbuilding',
    location: 'Talegaon MIDC, Pune',
    trade: 'Machinist / Fitter',
    midcZone: 'Talegaon MIDC',
    shiftDetails: '1st Shift (8:00 AM - 5:00 PM)',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 5,
    maxExperience: 10,
    salaryMin: 35000,
    salaryMax: 48000,
    openings: 7,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Horizontal Floor Boring machine operators required for machining heavy defense armor structures and naval engine beds.',
    responsibilities: [
      'Setup and operate large CNC Floor Boring machines (Heidenhain / Siemens).',
      'Clamp multi-ton fabrication structures safely.',
      'Maintain tight tolerances (within 20 microns).'
    ],
    requirements: [
      'ITI Machinist / Turner or IGTR Diploma.',
      '5+ years experience on floor boring or large gantry CNC mills.',
      'Proficiency in Heidenhain iTNC 530 control systems.'
    ],
    skills: ['Floor Boring', 'CNC Heavy Machining', 'Heidenhain', 'Defense Specs', 'Precision Alignment'],
    perks: ['Defense Project Risk Allowance', 'Family Health Policy']
  },
  {
    company: 'Godrej Process Equipment',
    companyLogo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#047857',
    title: 'Boiler & Pressure Vessel Fitter',
    industry: 'Process Equipment & Oil/Gas',
    location: 'Shirwal MIDC / Vikhroli, Pune',
    trade: 'Pipe Fitter / Fabricator',
    midcZone: 'Shirwal MIDC',
    shiftDetails: 'General Shift',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 26000,
    salaryMax: 35000,
    openings: 15,
    filledOpenings: 4,
    status: 'APPROVED',
    description: 'Looking for experienced heavy fabricators for shell rolling, dish end fitment, and nozzle orientation on ASME pressure vessels.',
    responsibilities: [
      'Read complex GA drawings and shell development layouts.',
      'Perform gas cutting, beveling, and tack welding fitments.',
      'Prepare vessel joints for X-ray quality welding.'
    ],
    requirements: [
      'ITI Fitter / Sheet Metal Worker.',
      '3+ years in heavy pressure vessel / heat exchanger fabrication shop.',
      'Familiarity with ASME Section VIII Code standards.'
    ],
    skills: ['Fabrication', 'ASME Vessels', 'Pipe Fitting', 'Beveling', 'Layout Development'],
    perks: ['Overtime Pay (2x)', 'Subsidized Canteen', 'Safety Insurance']
  },
  {
    company: 'Schindler Elevators India',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#c026d3',
    title: 'Elevator Installation & Field Technician',
    industry: 'Elevators & Building Systems',
    location: 'Chakan MIDC / Citywide Pune',
    trade: 'Electrical / Elevator Tech',
    midcZone: 'Chakan MIDC',
    shiftDetails: 'General Field Hours',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 1,
    maxExperience: 4,
    salaryMin: 21000,
    salaryMax: 29000,
    openings: 22,
    filledOpenings: 9,
    status: 'APPROVED',
    description: 'Field technicians required for mechanical elevator guide rail erection, wiring, and lift control panel commissioning.',
    responsibilities: [
      'Erect lift shaft guide rails, traction motors, and elevator cabins.',
      'Route wiring harnesses and connect safety door sensors.',
      'Conduct load testing and elevator ride comfort checks.'
    ],
    requirements: [
      'ITI Electrician / Wireman / Elevator Tech.',
      '1+ year experience in elevator installation or maintenance.',
      'No fear of heights (working in elevator shafts up to 20 floors).'
    ],
    skills: ['Elevator Wiring', 'Lift Shaft Erection', 'Control Panel', 'Motor Drives', 'Field Service'],
    perks: ['Daily Conveyance Allowance', 'Mobile Phone Allowance']
  },
  {
    company: 'Forbes Marshall Energy Efficiency',
    companyLogo: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0284c7',
    title: 'Industrial Steam Trap Calibration Tech',
    industry: 'Instrumentation & Process Control',
    location: 'Kasarwadi, Pune',
    trade: 'Instrumentation Mechanic',
    midcZone: 'Kasarwadi Industrial Belt',
    shiftDetails: 'General Shift',
    overtime: false,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 25000,
    salaryMax: 33000,
    openings: 9,
    filledOpenings: 3,
    status: 'APPROVED',
    description: 'Technicians needed for manufacturing, assembling, and hydro-testing control valves, steam traps, and flow meters.',
    responsibilities: [
      'Assemble pneumatic actuator valves and steam traps.',
      'Perform hydrostatic pressure testing up to 100 bar.',
      'Calibrate 4-20mA smart valve positioners.'
    ],
    requirements: [
      'ITI Instrument Mechanic or Diploma in Instrumentation.',
      '2+ years experience in industrial valve / flow meter assembly.',
      'Knowledge of pressure gauges & pneumatic calibrators.'
    ],
    skills: ['Instrumentation', 'Control Valves', 'Hydro Testing', 'Steam Traps', 'Calibration'],
    perks: ['Bonus Plan', 'Pension Scheme', 'Medical Insurance']
  },
  {
    company: 'Minda Corporation Automotive Systems',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#15803d',
    title: 'Automotive Wiring Harness Operator',
    industry: 'Auto Components / Electrical',
    location: 'Nanekarwadi / Chakan MIDC, Pune',
    trade: 'Electrician / Wireman',
    midcZone: 'Nanekarwadi Chakan',
    shiftDetails: '1st & 2nd Rotational Shifts',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: '1 Year Apprentice / Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 0,
    maxExperience: 3,
    salaryMin: 15500,
    salaryMax: 20500,
    openings: 50,
    filledOpenings: 18,
    status: 'APPROVED',
    description: 'Hiring freshers and junior technicians for auto wiring harness layout assembly, wire crimping, and continuity testing.',
    responsibilities: [
      'Route color-coded wires on assembly jig boards.',
      'Operate automatic terminal crimping machines.',
      'Conduct 100% electrical continuity testing on test benches.'
    ],
    requirements: [
      '10th / 12th / ITI Electrician or Wireman.',
      'Fresher or up to 3 years experience.',
      'Color perception (must differentiate wire color coding clearly).'
    ],
    skills: ['Wiring Harness', 'Crimping', 'Continuity Test', 'Wire Layout', 'Jig Assembly'],
    perks: ['Free Bus Facility', 'Subsidized Canteen', 'Monthly Attendance Bonus']
  },
  {
    company: 'Alfa Laval India Process Systems',
    companyLogo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0369a1',
    title: 'Plate Heat Exchanger Assembly Technician',
    industry: 'Food Processing & Chemical Machinery',
    location: 'Dapodi / Sarole MIDC, Pune',
    trade: 'Fitter / Machinist',
    midcZone: 'Dapodi Industrial Area',
    shiftDetails: 'General Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 5,
    salaryMin: 24000,
    salaryMax: 32000,
    openings: 11,
    filledOpenings: 4,
    status: 'APPROVED',
    description: 'Technicians required for assembling high-pressure stainless steel plate heat exchangers and high-speed centrifuges.',
    responsibilities: [
      'Fit titanium & SS plates with EPDM rubber gaskets.',
      'Tighten tie-bolts using hydraulic torque wrenches.',
      'Perform pneumatic leak testing under water.'
    ],
    requirements: [
      'ITI Fitter or Mechanical Diploma.',
      '2+ years in pump, valve, or heat exchanger manufacturing.',
      'Experience using hydraulic torqueing tools.'
    ],
    skills: ['Heat Exchanger', 'Hydraulic Torqueing', 'Pneumatic Leak Test', 'Gasket Fitment', 'Fitter'],
    perks: ['Annual Increment', 'Mediclaim ₹3.5L']
  },
  {
    company: 'Gabriel India Shock Absorbers',
    companyLogo: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#e11d48',
    title: 'Robotic Welding Line Operator',
    industry: 'Automotive Suspension Systems',
    location: 'Kuruli / Chakan MIDC, Pune',
    trade: 'Welder / Robotics',
    midcZone: 'Kuruli Chakan',
    shiftDetails: 'Rotational Shifts',
    overtime: true,
    accommodation: true,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 1,
    maxExperience: 4,
    salaryMin: 19500,
    salaryMax: 26000,
    openings: 16,
    filledOpenings: 7,
    status: 'APPROVED',
    description: 'Operators needed for loading shock absorber struts onto ABB / Fanuc robotic welding cells and inspecting weld penetration.',
    responsibilities: [
      'Load auto components into robotic weld fixtures.',
      'Run robotic MIG welding cycles and clean weld spatter.',
      'Check weld bead profile using cut-and-etch macro samples.'
    ],
    requirements: [
      'ITI Welder or Diploma in Production.',
      '1+ year operating robotic welding stations.',
      'Basic robot teach pendant knowledge is an advantage.'
    ],
    skills: ['Robotic Welding', 'ABB Robot', 'MIG Welding', 'Strut Assembly', 'Weld Inspection'],
    perks: ['Shift Allowance', 'Free Canteen', 'Safety Boots Provided']
  },
  {
    company: 'Sandvik Mining & Rock Technology',
    companyLogo: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#ca8a04',
    title: 'Tungsten Carbide Tool Inserts Grinding Tech',
    industry: 'Mining Equipment & Cutting Tools',
    location: 'Patas MIDC / Swargate, Pune',
    trade: 'Grinder / Machinist',
    midcZone: 'Patas Industrial Zone',
    shiftDetails: '1st Shift (7:00 AM - 3:30 PM)',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: false,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 3,
    maxExperience: 7,
    salaryMin: 27000,
    salaryMax: 37000,
    openings: 7,
    filledOpenings: 2,
    status: 'APPROVED',
    description: 'Grinding technicians needed for Agathon CNC insert grinding machines producing carbide cutting tool tips.',
    responsibilities: [
      'Operate CNC diamond wheel insert grinding machines.',
      'Inspect rake angle, clearance angle, and hone radius under optical comparator.',
      'Maintain diamond wheel dressing schedules.'
    ],
    requirements: [
      'ITI Machinist or Tool & Die Maker.',
      '3+ years in tungsten carbide tool insert grinding shop.',
      'Knowledge of PVD / CVD coating prep.'
    ],
    skills: ['Carbide Tools', 'CNC Grinding', 'Agathon', 'Optical Comparator', 'Cutting Inserts'],
    perks: ['Quarterly Performance Incentive', 'Free Bus']
  },
  {
    company: 'Wilmott Automation Controls',
    companyLogo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#7c3aed',
    title: 'Control Panel Wireman & Testing Technician',
    industry: 'Electrical Control Panels',
    location: 'Pirangut Industrial Zone, Pune',
    trade: 'Electrician / Panel Wireman',
    midcZone: 'Pirangut MIDC',
    shiftDetails: 'General Shift',
    overtime: true,
    accommodation: true,
    busFacility: false,
    canteen: true,
    joiningBonus: false,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 1,
    maxExperience: 5,
    salaryMin: 18000,
    salaryMax: 25000,
    openings: 15,
    filledOpenings: 6,
    status: 'APPROVED',
    description: 'Wiremen required for assembling PLC panels, MCC (Motor Control Centers), and VFD drive cabinets according to schematic drawings.',
    responsibilities: [
      'Lay ducting, DIN rails, MCBs, contactors, and relays in control cabinets.',
      'Ferrule wire ends and route wiring neatly with cable ties.',
      'Perform power-on high-pot voltage testing and loop checks.'
    ],
    requirements: [
      'ITI Electrician / Wireman.',
      '1+ year panel wiring experience.',
      'Ability to read electrical schematic circuit diagrams.'
    ],
    skills: ['Panel Wiring', 'MCC Panel', 'Electrical Schematic', 'Ferrule Crimping', 'VFD Drives'],
    perks: ['Overtime Pay', 'Room Facility', 'PF & ESI']
  },
  {
    company: 'Atlas Copco Compressor Technique',
    companyLogo: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=150&q=70&fm=webp',
    companyColor: '#0284c7',
    title: 'Rotary Screw Air Compressor Assembly Fitter',
    industry: 'Compressors & Pneumatic Tools',
    location: 'Dapodi / Chakan MIDC, Pune',
    trade: 'Fitter / Pneumatics',
    midcZone: 'Dapodi Industrial Belt',
    shiftDetails: '1st Shift',
    overtime: true,
    accommodation: false,
    busFacility: true,
    canteen: true,
    joiningBonus: true,
    attendanceBonus: true,
    contractDuration: 'Permanent',
    jobType: 'Full-time',
    workMode: 'On-site',
    minExperience: 2,
    maxExperience: 6,
    salaryMin: 23000,
    salaryMax: 32000,
    openings: 12,
    filledOpenings: 4,
    status: 'APPROVED',
    description: 'Assembly fitters required for mounting screw elements, drive motors, oil separators, and air coolers onto skid frames.',
    responsibilities: [
      'Fit rotary screw element rotors into compressor casing.',
      'Align electric motor drive pulleys with laser alignment tool.',
      'Conduct 8-hour continuous air pressure testing.'
    ],
    requirements: [
      'ITI Fitter or Turner.',
      '2+ years experience in compressor or pump assembly line.',
      'Knowledge of laser shaft alignment tools.'
    ],
    skills: ['Air Compressor', 'Rotary Screw', 'Laser Alignment', 'Pneumatics', 'Skid Assembly'],
    perks: ['Subsidized Meals', 'Attendance Bonus ₹1,200', 'Group Insurance']
  }
];

async function seed20MoreJobs() {
  console.log('🚀 Seeding 20 Additional Industry-Grade Jobs with WebP Logos & Specs...');

  try {
    let employerRes = await pool.query("SELECT id FROM users WHERE role = 'EMPLOYER' LIMIT 1;");
    let employerId = employerRes.rows[0]?.id;

    if (!employerId) {
      const newEmployer = await pool.query(`
        INSERT INTO users (email, password_hash, name, phone, role, company_name, status)
        VALUES ('recruiter.bulk@jobmarket.com', '$2b$10$X7WzD.4.O7gD7qMv/xW6U.rN81lKzP3eZ1zQZ.X61W2Z3Y4X5Y6Z7', 'Enterprise Recruiter', '9988776655', 'EMPLOYER', 'Industrial Enterprises Corp', 'APPROVED')
        RETURNING id;
      `);
      employerId = newEmployer.rows[0].id;
    }

    let count = 0;
    for (const job of ADDITIONAL_20_JOBS) {
      const query = `
        INSERT INTO jobs (
          employer_id, company, company_logo, company_color, title, industry, location,
          trade, midc_zone, shift_details, overtime, accommodation, bus_facility, canteen,
          joining_bonus, attendance_bonus, contract_duration, job_type, work_mode,
          min_experience, max_experience, salary_min, salary_max, openings, filled_openings,
          status, description, responsibilities, requirements, skills, perks, posted_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
          $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, NOW() - ($32 || ' hours')::INTERVAL
        );
      `;

      const values = [
        employerId,
        job.company,
        job.companyLogo,
        job.companyColor,
        job.title,
        job.industry,
        job.location,
        job.trade,
        job.midcZone,
        job.shiftDetails,
        job.overtime,
        job.accommodation,
        job.busFacility,
        job.canteen,
        job.joiningBonus,
        job.attendanceBonus,
        job.contractDuration,
        job.jobType,
        job.workMode,
        job.minExperience,
        job.maxExperience,
        job.salaryMin,
        job.salaryMax,
        job.openings,
        job.filledOpenings,
        job.status,
        job.description,
        JSON.stringify(job.responsibilities),
        JSON.stringify(job.requirements),
        JSON.stringify(job.skills),
        JSON.stringify(job.perks),
        (count * 2).toString() // staggered posting times
      ];

      await pool.query(query, values);
      count++;
      console.log(`[${count}/20] ✅ Inserted: "${job.title}" at ${job.company}`);
    }

    console.log('🎉 Successfully added 20 new jobs with company logos to database!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Error seeding 20 jobs:', err);
    process.exit(1);
  }
}

seed20MoreJobs();
