-- UP Migration: 007_add_missing_profile_fields.sql
ALTER TABLE users ADD COLUMN IF NOT EXISTS headline VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills TEXT[];
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_shift VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS requires_bus BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS requires_accommodation BOOLEAN DEFAULT FALSE;
