ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS interview_date VARCHAR(50),
ADD COLUMN IF NOT EXISTS interview_time VARCHAR(50),
ADD COLUMN IF NOT EXISTS venue_address TEXT,
ADD COLUMN IF NOT EXISTS maps_link VARCHAR(500);
