ALTER TABLE jobs ADD COLUMN IF NOT EXISTS hiring_method VARCHAR(50) DEFAULT 'STANDARD';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS walk_in_start_time VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS walk_in_end_time VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS walk_in_contact_person VARCHAR(100);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS walk_in_contact_number VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS walk_in_documents TEXT;
